import type { Contact, Company, Workspace, Profile } from "@/types";
import { isDemoMode as checkDemoMode } from "@/lib/app-config";

export const DEMO_WORKSPACE: Workspace = {
  id: "demo-workspace-001",
  name: "Acme Ventures",
  slug: "acme-ventures",
  logo_url: null,
  plan: "pro",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_PROFILE: Profile = {
  id: "demo-user-001",
  email: "demo@potentially.ai",
  name: "Alex Morgan",
  avatar_url: null,
  bio: "Founder & relationship builder",
  title: "CEO",
  linkedin_url: "https://linkedin.com/in/alexmorgan",
  is_admin: false,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_COMPANIES: Company[] = [
  {
    id: "co-001",
    workspace_id: "demo-workspace-001",
    name: "Stripe",
    domain: "stripe.com",
    industry: "Fintech",
    size: "5000+",
    description: "Online payment processing",
    linkedin_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "co-002",
    workspace_id: "demo-workspace-001",
    name: "Anthropic",
    domain: "anthropic.com",
    industry: "AI",
    size: "500-1000",
    description: "AI safety company",
    linkedin_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "co-003",
    workspace_id: "demo-workspace-001",
    name: "Sequoia Capital",
    domain: "sequoiacap.com",
    industry: "Venture Capital",
    size: "200-500",
    description: "Venture capital firm",
    linkedin_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "co-004",
    workspace_id: "demo-workspace-001",
    name: "Notion",
    domain: "notion.so",
    industry: "SaaS",
    size: "500-1000",
    description: "All-in-one workspace",
    linkedin_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "co-005",
    workspace_id: "demo-workspace-001",
    name: "Plaid",
    domain: "plaid.com",
    industry: "Fintech",
    size: "1000-5000",
    description: "Financial data network",
    linkedin_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "ct-001",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Sarah Chen",
    first_name: "Sarah",
    last_name: "Chen",
    title: "CTO",
    email: "sarah.chen@stripe.com",
    phone: null,
    linkedin_url: "https://linkedin.com/in/sarahchen",
    company_id: "co-001",
    company_name: "Stripe",
    location: "San Francisco, CA",
    bio: "Engineering leader with 15+ years in fintech infrastructure.",
    tags: ["fintech", "engineering", "cto"],
    source: "google_contacts",
    strength_score: 85,
    last_interaction_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-002",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "James Park",
    first_name: "James",
    last_name: "Park",
    title: "Founder & CEO",
    email: "james@anthropic.com",
    phone: null,
    linkedin_url: "https://linkedin.com/in/jamespark",
    company_id: "co-002",
    company_name: "Anthropic",
    location: "San Francisco, CA",
    bio: "Building safe AI systems. Previously at Google Brain.",
    tags: ["ai", "founder", "ceo"],
    source: "google_contacts",
    strength_score: 72,
    last_interaction_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-003",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Emily Rodriguez",
    first_name: "Emily",
    last_name: "Rodriguez",
    title: "Partner",
    email: "emily@sequoiacap.com",
    phone: null,
    linkedin_url: "https://linkedin.com/in/emilyrodriguez",
    company_id: "co-003",
    company_name: "Sequoia Capital",
    location: "Menlo Park, CA",
    bio: "Investing in enterprise SaaS and fintech. Board member at 12 companies.",
    tags: ["vc", "investor", "enterprise"],
    source: "google_calendar",
    strength_score: 90,
    last_interaction_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-004",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Michael Torres",
    first_name: "Michael",
    last_name: "Torres",
    title: "VP Engineering",
    email: "michael@notion.so",
    phone: null,
    linkedin_url: "https://linkedin.com/in/michaeltorres",
    company_id: "co-004",
    company_name: "Notion",
    location: "New York, NY",
    bio: "Scaling engineering teams. Passionate about developer tools.",
    tags: ["engineering", "saas", "vp"],
    source: "gmail",
    strength_score: 65,
    last_interaction_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-005",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Lisa Wang",
    first_name: "Lisa",
    last_name: "Wang",
    title: "Head of Product",
    email: "lisa@plaid.com",
    phone: null,
    linkedin_url: "https://linkedin.com/in/lisawang",
    company_id: "co-005",
    company_name: "Plaid",
    location: "San Francisco, CA",
    bio: "Product leader in fintech. Former PM at Square.",
    tags: ["product", "fintech", "head"],
    source: "csv",
    strength_score: 78,
    last_interaction_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-006",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "David Kim",
    first_name: "David",
    last_name: "Kim",
    title: "Co-Founder",
    email: "david@fintechstartup.io",
    phone: null,
    linkedin_url: "https://linkedin.com/in/davidkim",
    company_id: null,
    company_name: "FinTech Startup",
    location: "Austin, TX",
    bio: "Building the future of B2B payments. Raised Series A.",
    tags: ["founder", "fintech", "startup"],
    source: "google_contacts",
    strength_score: 55,
    last_interaction_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    metadata: { funding: "Series A" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-007",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Rachel Foster",
    first_name: "Rachel",
    last_name: "Foster",
    title: "Chief Revenue Officer",
    email: "rachel@enterprise.co",
    phone: null,
    linkedin_url: "https://linkedin.com/in/rachelfoster",
    company_id: null,
    company_name: "Enterprise Co",
    location: "Chicago, IL",
    bio: "Revenue leader with expertise in enterprise sales.",
    tags: ["sales", "enterprise", "cro"],
    source: "outlook",
    strength_score: 60,
    last_interaction_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ct-008",
    workspace_id: "demo-workspace-001",
    owner_id: "demo-user-001",
    full_name: "Tom Bradley",
    first_name: "Tom",
    last_name: "Bradley",
    title: "Founder",
    email: "tom@aitech.io",
    phone: null,
    linkedin_url: "https://linkedin.com/in/tombradley",
    company_id: null,
    company_name: "AI Tech",
    location: "Seattle, WA",
    bio: "AI entrepreneur. Previously sold startup to Microsoft.",
    tags: ["founder", "ai", "exit"],
    source: "google_contacts",
    strength_score: 70,
    last_interaction_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    metadata: { funding: "Seed" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SUGGESTED_PROMPTS = [
  "Find founders connected to me",
  "Find CTOs working in fintech",
  "Who can introduce me to Stripe?",
  "Show people from my network who raised funding",
  "Find VCs in my network",
  "Who did I meet last month?",
];

export function isDemoMode() {
  return checkDemoMode();
}
